// ESLint flat-config completion is an explicit opt-in. Copy its augmentation
// into dual declaration files because @eslint/core publishes separate ESM and
// CommonJS types. The main declaration entry stays free of ESLint references.

import fs from "node:fs"
import path from "node:path"
import { fileURLToPath } from "node:url"

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..")
const dist = path.join(root, "dist")
const source = fs.readFileSync(path.join(root, "src/eslint.ts"), "utf8")
const header =
  "// Generated by scripts/postbuild.mjs from src/eslint.ts. Do not edit.\n"
fs.writeFileSync(
  path.join(dist, "eslint.d.ts"),
  '/// <reference path="./eslint.d.cts" />\n' + header + source
)
fs.writeFileSync(path.join(dist, "eslint.d.cts"), header + source)
fs.rmSync(path.join(dist, "tailwind-worker.d.ts"), { force: true })
console.log("postbuild: optional eslint augmentation written to dist")
